version: '3.8'

services:
  sdk:
    build: .
    volumes:
      - .:/app
      - pnpm-store:/root/.local/share/pnpm/store
      - node_modules:/app/node_modules
    command: pnpm run dev
    env_file:
      - .env
    environment:
      - TEST_ENV=${TEST_ENV}
      - EMBER_ENDPOINT=${EMBER_ENDPOINT}
      - EMBER_API_KEY=${EMBER_API_KEY}
    
  proto:
    build: .
    volumes:
      - .:/app
      - pnpm-store:/root/.local/share/pnpm/store
      - node_modules:/app/node_modules
    command: >
      sh -c "pnpm install && pnpm run generate-proto"

volumes:
  node_modules:
  pnpm-store: 