name: Release Ember SDK Typescript

on:
  workflow_dispatch:
  push:
    branches: ['main', 'latest']

permissions:
  contents: read

jobs:
  release:
    name: release-sdk
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install protoc and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          # Ensure protoc is available and print version
          protoc --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm run build

      - name: Release to GitHub and NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
